# https://www.gitpod.io/docs
# https://www.gitpod.io/docs/config-start-tasks
tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install --yes --no-install-recommends ca-certificates build-essential git python3 libgd-dev libsqlite3-dev
      make
    command: |
      ./build/release/src/iqdb http 0.0.0.0 5588 iqdb.sqlite
    openMode: split-right

# https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5588
    visibility: public
